version: "3.9"
services:
  backlink:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8082:5000
    env_file:
      - .env
    volumes:
      - "./watch_dir:/code/watch_dir"
      - "./files:/code/files"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    environment:
      ADMINER_DESIGN: dracula
    volumes:
      - "./login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php"
      - "./files:/var/www/html/files"
